### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by katieannemills** [DSSatPitt/studyGroup#1]
Hi there - thanks for forking the Study Group repo! Let me know if you have any questions on how to get started - happy to help. First things first - now that you've got the website all set up, things go smoothest when you've got a team of people helping organize events and reach out to your community. Find some co-organizers and you'll be off to a great start!

For (tons) more information, don't miss the [Study Group Handbook](http://mozillascience.github.io/studyGroupHandbook/index.html), which includes all the collected wisdom on organizing a Study Group (and a handy link to lesson plans in the appendix).

Finally, jump on the [organzier's mailing list](https://mail.mozilla.org/listinfo/msl-study-groups) - this list is for Study Group leaders worldwide to interact with each other, and we use it to send invitations to our monthly virtual meeting to share back questions and ideas.

Let me know when you've got your first meeting booked, and I'll add you to the global [Map of Study Groups](https://github.com/mozillascience/studyGroupLessons/blob/master/whereWeAre.geojson) - thanks again, let me know!

**Comment by mcburton** [comment]
Hey Bill,
Thanks for reaching out. I am just getting started with the study group. We haven't launched it yet here at Pitt, but I'll be sure to register with Mozilla when we do!

Thanks for putting together these resources. The Handbook is very useful. I'll be sure to join the mailing list too. 

cheers

**Comment by katieannemills** [comment]
Heya - it's been a while, how's things? Let me know where you're at, happy to help if I can!

**Comment by mcburton** [comment]
Hey Bill, I am currently in stealth mode. We are waiting on some construction projects to finish in the Library so we have space and screens for our meetings. My plan has been to launch on 2016 at the beginning of the semester. I'll be sure to register once we are meeting!

**Comment by katieannemills** [comment]
:+1: that's awesome, looking forward to it!
